### ISSUE TITLE
conffile prompt and needs to be upgraded manually

### ISSUE THREAD

**Issue by memelet** [jnv/ansible-role-unattended-upgrades#56] opened 2018-11-12 19:08 UTC
I'm getting emails daily
```
/etc/cron.daily/apt:
Package 'apport' has conffile prompt and needs to be upgraded manually
```
I have `unattended_mail:false` (default), and `unattended_autofix_interrupted_dpkg:true` (default).

I'm not quite sure what needs to be done.

**Comment by jnv** [comment] 2018-11-13 11:18
Hi, this is not a problem specific to this role, but `unattended-upgrades` behavior. You need to do what does it say, i.e. run `apt upgrade apport`, because there are some changes in apport's configuration files which need to be confirmed manually.

Alternatively you can set default behavior for unattended upgrades to keep or overwrite configuration files automatically, see for example [here](https://unix.stackexchange.com/q/138751/40929). [This post](https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/) is also useful and might give you some insight.
In the context of this role, you'd set `unattended_dpkg_options` variable like this, to keep old configuration files:

```
unattended_dpkg_options: ["--force-confdef", "--force-confold"]
```

I will close this issue as it is not something directly applicable to this role.

**Closed by jnv** 2018-11-13 11:18 UTC

**Comment by memelet** [comment] 2018-11-13 18:46
Thanks `unattended_dpkg_options` is exactly what I was missing.
